### ISSUE TITLE
Formatting of constructors

### ISSUE THREAD

**Issue by halverneus** [logavanc/largs#4]
This is a recommendation, not a requirement. Instead of:

func NewSomething(x, y int) *Something {
  this := new(Something)
  this.x = x
  this.y = y
  return this
}

I recommend:

func NewSomething(x, y int) *Something {
  this := Something{
    x: x,
    y: y,
  }
  return &this
}

**Comment by logavanc** [comment]
Is that a performance thing or a readability thing?

**Comment by halverneus** [comment]
Readability. It is forbidden in most languages, but can be a useful way to
populate structs in a readable fashion. Again, not a requirement, but I
have personally developed a preference for it.

**Comment by logavanc** [comment]
Just so I am clear, this is essentially not using the `new()` function, right?
Also, I opted for this syntax instead:

``` go
this := &Something{
    x: x,
    y: y,
}
return
```

**Comment by halverneus** [comment]
That is correct, and your chosen syntax should work equally well.
